-- 実行PL/SQL
DECLARE
	vIDCount NUMBER(10) := 0;
	vDepartmentID VARCHAR(20) := '';

BEGIN

	/* ロール権限データ削除  */
	/* 試験車管理システム利用者の人での割り当て(群馬ユーザー)は除外  */
	DELETE FROM DEVPLAN.ROLL_AUTH WHERE NOT(ROLL_ID = '14' AND PERSONEL_ID IS NOT NULL);

	/* MAXID取得 */
	SELECT MAX(ID) INTO vIDCount FROM DEVPLAN.ROLL_AUTH;

	/* 職制の部ID取得 */
	FOR rec IN (
		SELECT DISTINCT
			DEPARTMENT_ID
			FROM
				DEPARTMENT_DATA 
			WHERE
				DEPARTMENT_ID NOT IN ('57','69','70','73','74','75','81') -- STC以外
				AND FLAG_EXIST = 1  -- 有効のみ
			ORDER BY
				DEPARTMENT_ID
	) LOOP

		/* 職制ロールへ役職の割り当て（部） */
		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,rec.DEPARTMENT_ID,NULL,NULL,'課長',NULL,'1',SYSDATE,'00001',NULL,NULL);
		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,rec.DEPARTMENT_ID,NULL,NULL,'主幹',NULL,'1',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 職制ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			PERSONEL_ID
			FROM
				PERSONEL_LIST 
			WHERE
				ACCESS_LEVEL IN ('00') -- 職制
				AND OFFICIAL_POSITION NOT IN ('課長', '主幹')
				AND STATUS_CODE = 'a' -- a:在籍
			ORDER BY
				PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'1',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 担当ロールへ役職の割り当て（部） */
	vIDCount := vIDCount + 1;
	INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,'担当',NULL,'2',SYSDATE,'00001',NULL,NULL);
	vIDCount := vIDCount + 1;
	INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,'係長',NULL,'2',SYSDATE,'00001',NULL,NULL);

	/* 担当ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			PERSONEL_ID
			FROM
				PERSONEL_LIST 
			WHERE
				ACCESS_LEVEL IN ('10') -- 担当
				AND OFFICIAL_POSITION NOT IN ('担当', '係長')
				AND STATUS_CODE = 'a' -- a:在籍
			ORDER BY
				PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'2',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 一般ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				SECTION_GROUP_DATA B,
				SECTION_DATA C
			WHERE
				A.ACCESS_LEVEL IN ('20','21','30') -- 一般,一般(SJKAデータ入力),STC
				AND A.STATUS_CODE = 'a' -- a:在籍
				AND A.SECTION_GROUP_ID = B.SECTION_GROUP_ID
				AND B.SECTION_ID = C.SECTION_ID
				AND C.DEPARTMENT_ID NOT IN ('57','69','70','73','74','75','81') -- STC以外
				AND B.FLAG_EXIST = 1  -- 有効のみ
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'3',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* STCロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				SECTION_GROUP_DATA B,
				SECTION_DATA C
			WHERE
				A.ACCESS_LEVEL IN ('30') -- STC
				AND A.STATUS_CODE = 'a' -- a:在籍
				AND A.SECTION_GROUP_ID = B.SECTION_GROUP_ID
				AND B.SECTION_ID = C.SECTION_ID
				AND C.DEPARTMENT_ID IN ('57','69','70','73','74','75','81') -- STCのみ
				AND B.FLAG_EXIST = 1  -- 有効のみ
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'4',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* パートロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			PERSONEL_ID
			FROM
				PERSONEL_LIST 
			WHERE
				ACCESS_LEVEL IN ('40','41') -- パート,パート(SJKAデータ入力)
				AND STATUS_CODE = 'a' -- a:在籍
			ORDER BY
				PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'5',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* シニアロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			PERSONEL_ID
			FROM
				PERSONEL_LIST 
			WHERE
				ACCESS_LEVEL IN ('60') -- シニア
				AND STATUS_CODE = 'a' -- a:在籍
			ORDER BY
				PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'6',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 派遣ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			PERSONEL_ID
			FROM
				PERSONEL_LIST 
			WHERE
				ACCESS_LEVEL IN ('50') -- 派遣・外部委託
				AND STATUS_CODE = 'a' -- a:在籍
			ORDER BY
				PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'7',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* STC_カーシェア利用者ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				試験計画_カーシェア_FTS利用者 B
			WHERE
				A.STATUS_CODE = 'a' -- a:在籍
				AND A.PERSONEL_ID = B.PERSONEL_ID
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'8',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* PRINTSCREEN利用者ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT DISTINCT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				試験計画_PRINTSCREEN利用者 B
			WHERE
				A.STATUS_CODE = 'a' -- a:在籍
				AND A.LOGIN_ID = B.LOGIN_ID
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'9',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* システム管理者ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT DISTINCT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				試験計画_システム管理者 B
			WHERE
				A.STATUS_CODE = 'a' -- a:在籍
				AND A.PERSONEL_ID = B.PERSONEL_ID
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'10',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* カーシェア事務所ロールへの人の割り当て（人） */
	FOR rec IN (
		SELECT DISTINCT
			A.PERSONEL_ID
			FROM
				PERSONEL_LIST A,
				試験計画_外製車日程_管理者 B
			WHERE
				A.STATUS_CODE = 'a' -- a:在籍
				AND A.PERSONEL_ID = B.PERSONEL_ID
				AND B.正副 = 'スタッフ'
			ORDER BY
				A.PERSONEL_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,NULL,NULL,NULL,NULL,rec.PERSONEL_ID,'11',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 総括部署の部ID取得 */
	SELECT DEPARTMENT_ID INTO vDepartmentID FROM SECTION_DATA WHERE SECTION_ID = '19';

	/* 総括部署ロールへの部署の割り当て（部） */
	vIDCount := vIDCount + 1;
	INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,vDepartmentID,'19',NULL,NULL,NULL,'12',SYSDATE,'00001',NULL,NULL);

	/* SKC管理課の部ID取得 */
--	SELECT DEPARTMENT_ID INTO vDepartmentID FROM SECTION_DATA WHERE SECTION_ID = '12';

	/* SKC管理課ロールへの部署の割り当て（部） */
	vIDCount := vIDCount + 1;
	INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,'4',NULL,NULL,NULL,NULL,'13',SYSDATE,'00001',NULL,NULL);

	/* 試験車管理システム利用者ロールへの部の割り当て（部） */
	/*  三鷹ユーザー全員を対象  */
	FOR rec IN (
		SELECT
			DEPARTMENT_ID
			FROM
				DEPARTMENT_DATA
			WHERE
				ESTABLISHMENT = 't'
				AND FLAG_EXIST = 1  -- 有効のみ
			ORDER BY
				DEPARTMENT_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,rec.DEPARTMENT_ID,NULL,NULL,NULL,NULL,'14',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	/* 試験車管理システム管理者ロールへの部の割り当て（部） */
	FOR rec IN (
		SELECT DISTINCT 
			D.DEPARTMENT_ID,
			C.SECTION_ID,
			B.SECTION_GROUP_ID
			FROM
				管理部署マスタ A,
				SECTION_GROUP_DATA B,
				SECTION_DATA C,
				DEPARTMENT_DATA D
			WHERE
				A.担当ID = B.SECTION_GROUP_ID
				AND B.SECTION_ID = C.SECTION_ID
				AND C.DEPARTMENT_ID = D.DEPARTMENT_ID
				AND B.FLAG_EXIST = 1  -- 有効のみ
			ORDER BY
				D.DEPARTMENT_ID,
				C.SECTION_ID,
				B.SECTION_GROUP_ID
	) LOOP

		vIDCount := vIDCount + 1;
		INSERT INTO DEVPLAN.ROLL_AUTH VALUES (vIDCount,rec.DEPARTMENT_ID,rec.SECTION_ID,rec.SECTION_GROUP_ID,NULL,NULL,'15',SYSDATE,'00001',NULL,NULL);

	END LOOP;

	COMMIT;

EXCEPTION WHEN OTHERS THEN

	ROLLBACK;

END;
