-- 実行PL/SQL
BEGIN

	/* スケジュール利用車データ削除 */
	DELETE FROM DEVPLAN.SCHEDULE_CAR;

	/* スケジュール利用車(試験車日程)登録データ取得 */
	FOR rec IN (
		SELECT DISTINCT
			A.CATEGORY_ID,
			A.CATEGORY,
			B.管理票番号
			FROM
				TESTCAR_SCHEDULE_ITEM A,
				(SELECT CATEGORY_ID, MAX(管理票番号) 管理票番号 FROM 試験計画_外製車日程_車両リスト WHERE 管理票番号 IS NOT NULL GROUP BY CATEGORY_ID) B
			WHERE
				A.CATEGORY_ID = B.CATEGORY_ID(+)
			ORDER BY
				A.CATEGORY_ID
	) LOOP

	INSERT INTO DEVPLAN.SCHEDULE_CAR (CATEGORY_ID,管理票番号,備考,INPUT_DATETIME,INPUT_PERSONEL_ID) VALUES (rec.CATEGORY_ID,rec.管理票番号,rec.CATEGORY,SYSDATE,'00001');

	END LOOP;

	/* スケジュール利用車(カーシェア日程)登録データ取得 */
	FOR rec IN (
		SELECT DISTINCT
			A.CATEGORY_ID,
			A.CATEGORY,
			B.管理票番号
			FROM
				CARSHARING_SCHEDULE_ITEM A,
				(SELECT CATEGORY_ID, MAX(管理票番号) 管理票番号 FROM 試験計画_外製車日程_車両リスト WHERE 管理票番号 IS NOT NULL GROUP BY CATEGORY_ID) B
			WHERE
				A.CATEGORY_ID = B.CATEGORY_ID(+)
			ORDER BY
				A.CATEGORY_ID
	) LOOP

	INSERT INTO DEVPLAN.SCHEDULE_CAR (CATEGORY_ID,管理票番号,備考,INPUT_DATETIME,INPUT_PERSONEL_ID) VALUES (rec.CATEGORY_ID,rec.管理票番号,rec.CATEGORY,SYSDATE,'00001');

	END LOOP;

	/* スケジュール利用車(外製車日程)登録データ取得 */
	FOR rec IN (
		SELECT DISTINCT
			A.CATEGORY_ID,
			A.CATEGORY,
			B.管理票番号
			FROM
				OUTERCAR_SCHEDULE_ITEM A,
				(SELECT CATEGORY_ID, MAX(管理票番号) 管理票番号 FROM 試験計画_外製車日程_車両リスト WHERE 管理票番号 IS NOT NULL GROUP BY CATEGORY_ID) B
			WHERE
				A.CATEGORY_ID = B.CATEGORY_ID(+)
			ORDER BY
				A.CATEGORY_ID
	) LOOP

	INSERT INTO DEVPLAN.SCHEDULE_CAR (CATEGORY_ID,管理票番号,備考,INPUT_DATETIME,INPUT_PERSONEL_ID) VALUES (rec.CATEGORY_ID,rec.管理票番号,rec.CATEGORY,SYSDATE,'00001');

	END LOOP;

	COMMIT;

EXCEPTION WHEN OTHERS THEN

	ROLLBACK;

END;
