MERGE 
INTO トラック_情報 UPDATE_TBL 
  USING ( 
    SELECT
      ID
      , ROW_NUMBER() OVER (ORDER BY "NO") NEW_NUMBER 
    FROM
      トラック_情報 
    WHERE
      FLAG_定期便 = 1
  ) NEW_TBL 
    ON (UPDATE_TBL.ID = NEW_TBL.ID) WHEN MATCHED THEN UPDATE 
SET
  UPDATE_TBL.REGULAR_TIME_ID = NEW_TBL.NEW_NUMBER
