CREATE TABLE CONTACT_INFO 
(
  ID NUMBER(10) NOT NULL 
, GENERAL_CODE VARCHAR2(15) 
, PERSONEL_ID VARCHAR2(20) 
, TEL VARCHAR2(20) 
, STATUS VARCHAR2(10) 
, CATEGORY_ID NUMBER(10) 
, REMARKS VARCHAR2(1000 BYTE)
, FUNCTION_ID NUMBER(2) 
, CONSTRAINT CONTACT_INFO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN CONTACT_INFO.ID IS 'ID';

COMMENT ON COLUMN CONTACT_INFO.GENERAL_CODE IS '車系・開発符号';

COMMENT ON COLUMN CONTACT_INFO.STATUS IS '正副';

COMMENT ON COLUMN CONTACT_INFO.REMARKS IS '備考';

COMMENT ON COLUMN CONTACT_INFO.FUNCTION_ID IS '日程表種別';

