DROP TABLE "DEVPLAN"."PRODUCTION_CAR" PURGE;

CREATE TABLE "DEVPLAN"."PRODUCTION_CAR" 
   ("ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CAR_GROUP" VARCHAR2(10), 
	"CAR_TYPE" VARCHAR2(10), 
	"GENERAL_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"PROTOTYPE_PERIOD" VARCHAR2(20) NOT NULL ENABLE, 
	"VEHICLE" VARCHAR2(50) NOT NULL ENABLE, 
	"MODEL_CODE" VARCHAR2(50), 
	"DESTINATION" VARCHAR2(50), 
	"MAKER_NAME" VARCHAR2(50), 
	"CAR_MODEL" VARCHAR2(50), 
	"NAME_REMARKS" VARCHAR2(255), 
	"VEHICLE_NO" VARCHAR2(30), 
	"TEST_PURPOSE" VARCHAR2(255), 
	"COMPLETE_DATE" DATE, 
	"SECTION_GROUP_CODE" VARCHAR2(20), 
	"RESEARCH_NO" VARCHAR2(50), 
	"FIXED_ASSET_NO" VARCHAR2(10), 
	"CONSTRUCT_NO" VARCHAR2(10), 
	"DISPOSAL_PLAN_MONTH" DATE, 
	"MANAGEMENT_NO" VARCHAR2(10), 
	"HISTORY_NO" NUMBER(8,0), 
	"SERIAL_NO" VARCHAR2(10), 
	"ISSUE_NO" VARCHAR2(20), 
	"REVISION_NO" VARCHAR2(10), 
	"COMPLETE_REQUEST_DATE" DATE, 
	"TARGET" VARCHAR2(10), 
	"METHOD" VARCHAR2(10), 
	"REMARKS" VARCHAR2(255), 
	"ERROR_MESSAGE" VARCHAR2(255), 
	"ENTRY_DATETIME" DATE, 
	"ENTRY_PERSONEL_ID" VARCHAR2(20), 
	"INPUT_DATETIME" DATE, 
	"INPUT_PERSONEL_ID" VARCHAR2(20), 
	"CHANGE_DATETIME" DATE, 
	"CHANGE_PERSONEL_ID" VARCHAR2(20), 
	 CONSTRAINT "PK_PRODUCTION_CAR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"