CREATE TABLE EXCEPT_MONTHLY_INSPECTION (
	SECTION_GROUP_ID VARCHAR2(20) NOT NULL,  
	FLAG_月例点検 NUMBER(8, 0), 
	INPUT_DATETIME DATE,
	CONSTRAINT "EXCEPT_MONTHLY_INSPECTION_PKEY" PRIMARY KEY ("SECTION_GROUP_ID")
);