CREATE TABLE "DEVPLAN"."DUMMY_TESTCAR" 
   (	"データID" NUMBER(8,0) NOT NULL ENABLE, 
	"DELETE_FLG" CHAR(1), 
	"INPUT_DATETIME" DATE, 
	"INPUT_PERSONEL_ID" VARCHAR2(20), 
	 CONSTRAINT "PK_DUMMY_TESTCAR" PRIMARY KEY ("データID")
   )