--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ñÿójì˙-1åé-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FAVORITE_TEST_CAR
--------------------------------------------------------

  CREATE TABLE "DEVPLAN"."FAVORITE_TEST_CAR" 
   (	"ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PERSONEL_ID" VARCHAR2(20 BYTE), 
	"GENERAL_CODE" VARCHAR2(20 BYTE), 
	"TRIAL_TIME" VARCHAR2(20 BYTE), 
	"GOSHA" VARCHAR2(50 BYTE), 
	"CAR_TYPE" VARCHAR2(10 BYTE), 
	"DESTINATION" VARCHAR2(50 BYTE), 
	"STATUS_KBN" CHAR(1 BYTE), 
	"STATUS_OPEN_FLG" CHAR(1 BYTE), 
	"STATUS_CLOSE_FLG" CHAR(1 BYTE), 
	"INPUT_DATETIME" DATE, 
	"INPUT_PERSONEL_ID" VARCHAR2(20 BYTE), 
	"CHANGE_DATETIME" DATE, 
	"CHANGE_PERSONEL_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  DDL for Index IDX_FAVORITE_TEST_CAR_1
--------------------------------------------------------

  CREATE INDEX "DEVPLAN"."IDX_FAVORITE_TEST_CAR_1" ON "DEVPLAN"."FAVORITE_TEST_CAR" ("PERSONEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  DDL for Index PK_FAVORITE_TEST_CAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVPLAN"."PK_FAVORITE_TEST_CAR" ON "DEVPLAN"."FAVORITE_TEST_CAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  Constraints for Table FAVORITE_TEST_CAR
--------------------------------------------------------

  ALTER TABLE "DEVPLAN"."FAVORITE_TEST_CAR" ADD CONSTRAINT "PK_FAVORITE_TEST_CAR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE;
  ALTER TABLE "DEVPLAN"."FAVORITE_TEST_CAR" MODIFY ("PERSONEL_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVPLAN"."FAVORITE_TEST_CAR" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DEVPLAN"."FAVORITE_TEST_CAR" MODIFY ("ID" NOT NULL ENABLE);
