--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ñÿójì˙-1åé-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PC_AUTH
--------------------------------------------------------

  CREATE TABLE "DEVPLAN"."PC_AUTH" 
   (	"ID" NUMBER(10,0), 
	"PC_NAME" VARCHAR2(20 BYTE), 
	"FUNCTION_ID" NUMBER(5,0), 
	"INPUT_DATETIME" DATE, 
	"INPUT_PERSONEL_ID" VARCHAR2(20 BYTE), 
	"CHANGE_DATETIME" DATE, 
	"CHANGE_PERSONEL_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  DDL for Index PK_PC_AUTH
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVPLAN"."PK_PC_AUTH" ON "DEVPLAN"."PC_AUTH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  DDL for Index IDX_PC_AUTH_1
--------------------------------------------------------

  CREATE INDEX "DEVPLAN"."IDX_PC_AUTH_1" ON "DEVPLAN"."PC_AUTH" ("PC_NAME", "FUNCTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  Constraints for Table PC_AUTH
--------------------------------------------------------

  ALTER TABLE "DEVPLAN"."PC_AUTH" ADD CONSTRAINT "PK_PC_AUTH" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE;
  ALTER TABLE "DEVPLAN"."PC_AUTH" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVPLAN"."PC_AUTH" MODIFY ("PC_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEVPLAN"."PC_AUTH" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PC_AUTH
--------------------------------------------------------

  ALTER TABLE "DEVPLAN"."PC_AUTH" ADD CONSTRAINT "FK_PC_AUTH_1" FOREIGN KEY ("FUNCTION_ID")
	  REFERENCES "DEVPLAN"."FUNCTION_MST" ("ID") ENABLE;
