CREATE TABLE "DEVPLAN"."ROLL_AUTH" 
   (
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DEPARTMENT_ID" VARCHAR2(20), 
	"SECTION_ID" VARCHAR2(20), 
	"SECTION_GROUP_ID" VARCHAR2(20), 
	"OFFICIAL_POSITION" VARCHAR2(10), 
	"PERSONEL_ID" VARCHAR2(20), 
	"ROLL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"INPUT_DATETIME" DATE, 
	"INPUT_PERSONEL_ID" VARCHAR2(20), 
	"CHANGE_DATETIME" DATE, 
	"CHANGE_PERSONEL_ID" VARCHAR2(20), 
	 CONSTRAINT "PK_ROLL_AUTH" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE)
  SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA";