--------------------------------------------------------
--  ファイルを作成しました - 火曜日-1月-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCHEDULE_TO_XEYE
--------------------------------------------------------

  CREATE TABLE "DEVPLAN"."SCHEDULE_TO_XEYE" 
   (	"物品コード" VARCHAR2(10 BYTE), 
	"物品名" VARCHAR2(200 BYTE), 
	"物品名2" VARCHAR2(10 BYTE), 
	"物品名カナ" VARCHAR2(200 BYTE), 
	"物品区分コード" VARCHAR2(2 BYTE), 
	"備考" VARCHAR2(200 BYTE), 
	"ソート順" VARCHAR2(10 BYTE), 
	"1：有効／0：無効" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE_TO_XEYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVPLAN"."PK_SCHEDULE_TO_XEYE" ON "DEVPLAN"."SCHEDULE_TO_XEYE" ("物品コード") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  Constraints for Table SCHEDULE_TO_XEYE
--------------------------------------------------------

  ALTER TABLE "DEVPLAN"."SCHEDULE_TO_XEYE" ADD CONSTRAINT "PK_SCHEDULE_TO_XEYE" PRIMARY KEY ("物品コード")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE;
