--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - åéójì˙-7åé-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRUCK_REGULAR_MST
--------------------------------------------------------

  CREATE TABLE "DEVPLAN"."TRUCK_REGULAR_MST" 
   (	"ID" NUMBER, 
	"DISPLAY_NAME" VARCHAR2(20 BYTE), 
	"COLOR_CODE_R" NUMBER(3,0), 
	"COLOR_CODE_G" NUMBER(3,0), 
	"COLOR_CODE_B" NUMBER(3,0), 
	"FONT_COLOR_CODE_R" NUMBER(3,0), 
	"FONT_COLOR_CODE_G" NUMBER(3,0), 
	"FONT_COLOR_CODE_B" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
REM INSERTING into DEVPLAN.TRUCK_REGULAR_MST
SET DEFINE OFF;
Insert into DEVPLAN.TRUCK_REGULAR_MST (ID,DISPLAY_NAME,COLOR_CODE_R,COLOR_CODE_G,COLOR_CODE_B,FONT_COLOR_CODE_R,FONT_COLOR_CODE_G,FONT_COLOR_CODE_B) values (1,'8:30î≠',175,255,228,0,0,0);
Insert into DEVPLAN.TRUCK_REGULAR_MST (ID,DISPLAY_NAME,COLOR_CODE_R,COLOR_CODE_G,COLOR_CODE_B,FONT_COLOR_CODE_R,FONT_COLOR_CODE_G,FONT_COLOR_CODE_B) values (2,'9:10î≠',29,164,255,255,255,255);
--------------------------------------------------------
--  DDL for Index TRUCK_REGULAR_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVPLAN"."TRUCK_REGULAR_MST_PK" ON "DEVPLAN"."TRUCK_REGULAR_MST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA" ;
--------------------------------------------------------
--  Constraints for Table TRUCK_REGULAR_MST
--------------------------------------------------------

  ALTER TABLE "DEVPLAN"."TRUCK_REGULAR_MST" ADD CONSTRAINT "TRUCK_REGULAR_MST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERDATA"  ENABLE;
  ALTER TABLE "DEVPLAN"."TRUCK_REGULAR_MST" MODIFY ("ID" NOT NULL ENABLE);
