//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPlanWebAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPlanWebAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   failure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFailure {
            get {
                return ResourceManager.GetString("CommonFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   false に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFalse {
            get {
                return ResourceManager.GetString("CommonFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonSuccess {
            get {
                return ResourceManager.GetString("CommonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   true に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonTrue {
            get {
                return ResourceManager.GetString("CommonTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。システム管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03001 {
            get {
                return ResourceManager.GetString("KKE03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当データが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03002 {
            get {
                return ResourceManager.GetString("KKE03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDが登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03003 {
            get {
                return ResourceManager.GetString("KKE03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードに誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03004 {
            get {
                return ResourceManager.GetString("KKE03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が未入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03005 {
            get {
                return ResourceManager.GetString("KKE03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が数値として判断できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03006 {
            get {
                return ResourceManager.GetString("KKE03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が日付として判断できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03007 {
            get {
                return ResourceManager.GetString("KKE03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が桁数の最大値を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03008 {
            get {
                return ResourceManager.GetString("KKE03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された{0}はすでに登録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03009 {
            get {
                return ResourceManager.GetString("KKE03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にはこのシステムを利用する権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03010 {
            get {
                return ResourceManager.GetString("KKE03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が桁数の最大値を超えています。        ///半角{1}桁または全角{2}桁以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03011 {
            get {
                return ResourceManager.GetString("KKE03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にカタカナ以外の文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03012 {
            get {
                return ResourceManager.GetString("KKE03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のファイルパスが取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03013 {
            get {
                return ResourceManager.GetString("KKE03013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたユーザーIDはActiveDirectoryに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03014 {
            get {
                return ResourceManager.GetString("KKE03014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付範囲に誤りがあります。{0}に{1}を超える日付は入力できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03015 {
            get {
                return ResourceManager.GetString("KKE03015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に指定されたファイルは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03016 {
            get {
                return ResourceManager.GetString("KKE03016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が許容範囲値外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03017 {
            get {
                return ResourceManager.GetString("KKE03017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー・移動元の情報が正しく取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03018 {
            get {
                return ResourceManager.GetString("KKE03018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー・移動先に指定された開発符号は既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03019 {
            get {
                return ResourceManager.GetString("KKE03019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03020 {
            get {
                return ResourceManager.GetString("KKE03020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました。入力内容を確認して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03021 {
            get {
                return ResourceManager.GetString("KKE03021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03022 {
            get {
                return ResourceManager.GetString("KKE03022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されたスケジュールは重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03023 {
            get {
                return ResourceManager.GetString("KKE03023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本予約作業出来ませんでした。ご指定の予約要望は、既に本予約作業実施済のようです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03024 {
            get {
                return ResourceManager.GetString("KKE03024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期便丸数字の最大数20を超えています。いずれか不要な定期便を削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KKE03025 {
            get {
                return ResourceManager.GetString("KKE03025", resourceCulture);
            }
        }
    }
}
