//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPlan.UICommon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPlan.UICommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap DateStamp {
            get {
                object obj = ResourceManager.GetObject("DateStamp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap DateStampGray {
            get {
                object obj = ResourceManager.GetObject("DateStampGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;HolidaySetting&gt;
        ///    &lt;Holidays Key=&quot;NationalHoliday&quot; Name=&quot;休日&quot; ForeColor=&quot;Black&quot; BackColor=&quot;#CCCCCC&quot; Bold=&quot;False&quot; UnderLine=&quot;False&quot;&gt;
        ///        &lt;ForceHoliday Name=&quot;2017-04-01&quot; StartDate=&quot;2017-04-01T00:00:00&quot; EndDate=&quot;2017-04-01T00:00:00&quot; /&gt;
        ///        &lt;ForceHoliday Name=&quot;2017-04-02&quot; StartDate=&quot;2017-04-02T00:00:00&quot; EndDate=&quot;2017-04-02T00:00:00&quot; /&gt;
        ///        &lt;ForceHoliday Name=&quot;2017-04-08&quot; StartDate=&quot;2017-04-08T00:00:00&quot; EndDate=&quot;2017-04-08T00:00:00&quot; /&gt;
        ///        &lt;ForceHolid [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00001 {
            get {
                return ResourceManager.GetString("KKM00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00002 {
            get {
                return ResourceManager.GetString("KKM00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00003 {
            get {
                return ResourceManager.GetString("KKM00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件を一つ以上指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00004 {
            get {
                return ResourceManager.GetString("KKM00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果がありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00005 {
            get {
                return ResourceManager.GetString("KKM00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録していない変更があります。登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00006 {
            get {
                return ResourceManager.GetString("KKM00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00007 {
            get {
                return ResourceManager.GetString("KKM00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中の行を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00008 {
            get {
                return ResourceManager.GetString("KKM00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00009 {
            get {
                return ResourceManager.GetString("KKM00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00010 {
            get {
                return ResourceManager.GetString("KKM00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00011 {
            get {
                return ResourceManager.GetString("KKM00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認を解除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00012 {
            get {
                return ResourceManager.GetString("KKM00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認を解除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00013 {
            get {
                return ResourceManager.GetString("KKM00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同期してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00014 {
            get {
                return ResourceManager.GetString("KKM00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同期しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00015 {
            get {
                return ResourceManager.GetString("KKM00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お気に入りはこれ以上登録できません。（画面毎に5件まで） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00016 {
            get {
                return ResourceManager.GetString("KKM00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お気に入りが上限数に達していたたため、お気に入りの自動登録はできませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00017 {
            get {
                return ResourceManager.GetString("KKM00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了日は開始日以降の日付を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00018 {
            get {
                return ResourceManager.GetString("KKM00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象は1件のみ指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00019 {
            get {
                return ResourceManager.GetString("KKM00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたお気に入りは、開発符号の閲覧権限が無効となったため利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00020 {
            get {
                return ResourceManager.GetString("KKM00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに削除されています。再検索してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00021 {
            get {
                return ResourceManager.GetString("KKM00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上の項目を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00022 {
            get {
                return ResourceManager.GetString("KKM00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が数値として判断できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00025 {
            get {
                return ResourceManager.GetString("KKM00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が日付として判断できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00026 {
            get {
                return ResourceManager.GetString("KKM00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が桁数の最大値を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00027 {
            get {
                return ResourceManager.GetString("KKM00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にカタカナ以外の文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00028 {
            get {
                return ResourceManager.GetString("KKM00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に指定されたファイルは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00029 {
            get {
                return ResourceManager.GetString("KKM00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の書式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00032 {
            get {
                return ResourceManager.GetString("KKM00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スケジュールが登録されているため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00033 {
            get {
                return ResourceManager.GetString("KKM00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1行しかないため行削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00034 {
            get {
                return ResourceManager.GetString("KKM00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行数が上限数に達したため、行追加できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00035 {
            get {
                return ResourceManager.GetString("KKM00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お気に入りが1件も登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00036 {
            get {
                return ResourceManager.GetString("KKM00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebAPIに接続できませんでした。システム管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00037 {
            get {
                return ResourceManager.GetString("KKM00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用できる開発符号がないため、システムの利用ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00039 {
            get {
                return ResourceManager.GetString("KKM00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたお気に入りは、無効となったため利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00040 {
            get {
                return ResourceManager.GetString("KKM00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録権限対象のユーザーを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00041 {
            get {
                return ResourceManager.GetString("KKM00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のデータを削除します。よろしいですか？
        ///
        ///{0}：{1}
        ///{2}：{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00042 {
            get {
                return ResourceManager.GetString("KKM00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了日時は開始日時より後の日時を指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00043 {
            get {
                return ResourceManager.GetString("KKM00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの保存に失敗しました。
        ///同じ名前のファイルを開いている場合は閉じてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00044 {
            get {
                return ResourceManager.GetString("KKM00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移譲しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00045 {
            get {
                return ResourceManager.GetString("KKM00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00046 {
            get {
                return ResourceManager.GetString("KKM00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPS搭載車は1列目を右クリックし車両位置検索が行なえます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00047 {
            get {
                return ResourceManager.GetString("KKM00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを読み込みました。
        ///登録ボタンを押下して保存を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00048 {
            get {
                return ResourceManager.GetString("KKM00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り込んだすべてのデータは既存データとして存在している為、取り込みを中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00049 {
            get {
                return ResourceManager.GetString("KKM00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り込んだデータの号車は存在しないため、先に号車を追加してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00050 {
            get {
                return ResourceManager.GetString("KKM00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーマットが異なります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00051 {
            get {
                return ResourceManager.GetString("KKM00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録していないデータがありますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00052 {
            get {
                return ResourceManager.GetString("KKM00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り込んだすべてのデータの登録を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00053 {
            get {
                return ResourceManager.GetString("KKM00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象の行がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM00054 {
            get {
                return ResourceManager.GetString("KKM00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ５日を超える予約は出来ません。
        ///期間を修正して下さい。
        ///
        ///５日を超える予約が必要な場合は、各車系管理者にご相談下さい｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01001 {
            get {
                return ResourceManager.GetString("KKM01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験車日程を表示する権限がありません。
        ///
        ///
        ///試験車日程を見たい場合は、他部署情報閲覧権を所属長に設定してもらって下さい。
        ///
        ///他部署情報閲覧権はメインメニューの設定メニュー（閲覧権限）から設定出来ます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01002 {
            get {
                return ResourceManager.GetString("KKM01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示期間を変更することは出来ません。
        ///
        ///表示期間外に予約する必要がある場合は、各車系管理者にご依頼下さい｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01003 {
            get {
                return ResourceManager.GetString("KKM01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご指定の予約要望を最終調整結果画面にコピーし、本予約としました。
        ///
        ///最終調整結果画面を開いて、内容ご確認下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01004 {
            get {
                return ResourceManager.GetString("KKM01004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本予約作業出来ませんでした。
        ///
        ///まず仮予約作業を実施してから、本予約作業を実施して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01005 {
            get {
                return ResourceManager.GetString("KKM01005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終予約可能日を設定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01006 {
            get {
                return ResourceManager.GetString("KKM01006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーシェア日程上で3か月の表示期間をこえるスケジュールの閲覧は出来ません｡確認したい場合は､システム管理者にご連絡下さい｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01007 {
            get {
                return ResourceManager.GetString("KKM01007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示期間をこえるスケジュールの予約は出来ません。
        ///
        ///表示期間外に予約する必要がある場合は、各車系管理者にご依頼下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01008 {
            get {
                return ResourceManager.GetString("KKM01008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}か月の制限期間をこえるスケジュールの予約はできません。
        ///制限期間外に予約する必要がある場合は、各車系管理者にご依頼下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01009 {
            get {
                return ResourceManager.GetString("KKM01009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示期間を変更する事は出来ません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01010 {
            get {
                return ResourceManager.GetString("KKM01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のトラックは、現在予約を受け付けていません。
        ///
        ///不明の点がありましたら、{0}（{1}）までお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01011 {
            get {
                return ResourceManager.GetString("KKM01011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期便を 仮予約 しました。
        ///
        ///仮予約のままでは定期便を利用出来ませんのでご注意下さい。
        ///本予約とするには、管理者（{0} tel:{1}）まで承認をご依頼下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01012 {
            get {
                return ResourceManager.GetString("KKM01012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約を解除する権限がありません。
        ///
        ///定期便の本予約を解除出来るのは、管理部署(主)員のみです。
        ///予約を解除したい場合は管理者（{0} tel:{1}）までご依頼下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01013 {
            get {
                return ResourceManager.GetString("KKM01013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約解除する権限がありません。
        ///
        ///予約を解除出来るのは、予約者本人・依頼者・管理部署員のいずれかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01014 {
            get {
                return ResourceManager.GetString("KKM01014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約解除する権限がありません。
        ///
        ///予約を解除出来るのは、予約者・運転者・管理部署員のいずれかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01015 {
            get {
                return ResourceManager.GetString("KKM01015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トラックを予約しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01016 {
            get {
                return ResourceManager.GetString("KKM01016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他の指摘をコピーしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01017 {
            get {
                return ResourceManager.GetString("KKM01017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご指定の「往復空」便については、ドライバーの手配上、予約時間を
        ///AM便は前日17：00まで、PM便は当日11：40まで　としており、
        ///この時間は予約を受付けられません。ご了承願います。
        ///（片道が空となっている便の利用は可能です。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01018 {
            get {
                return ResourceManager.GetString("KKM01018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}～{1}のスケジュールを{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01019 {
            get {
                return ResourceManager.GetString("KKM01019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションの有効期限が切れました。
        ///ログイン画面より再度ログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01020 {
            get {
                return ResourceManager.GetString("KKM01020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}作成の項目です。
        ///{1}に管理を移譲してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01021 {
            get {
                return ResourceManager.GetString("KKM01021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理票No.{0}の車両に既に登録済みです。
        ///
        ///駐車場番号を別の車両に付与しなおす場合は、すでに登録済みの駐車場番号を変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01022 {
            get {
                return ResourceManager.GetString("KKM01022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理票の種類を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01023 {
            get {
                return ResourceManager.GetString("KKM01023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き不可のデータが含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM01024 {
            get {
                return ResourceManager.GetString("KKM01024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログオフしてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02001 {
            get {
                return ResourceManager.GetString("KKM02001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の期間は通常の週報の期間とは違います。間違っている場合は修正してください。
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02002 {
            get {
                return ResourceManager.GetString("KKM02002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象期間は1年以内で指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02003 {
            get {
                return ResourceManager.GetString("KKM02003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日時と終了日時が逆転するため、本操作は行なえません。
        ///スケジュール詳細より調整してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02004 {
            get {
                return ResourceManager.GetString("KKM02004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残業便の予約となります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02005 {
            get {
                return ResourceManager.GetString("KKM02005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記内容の予約を解除します。
        ///よろしいですか？
        ///
        ///号車・・・・{0}
        ///予約時間帯・・・・・・{1}発（{2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02006 {
            get {
                return ResourceManager.GetString("KKM02006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記内容の予約を解除します。
        ///よろしいですか？
        ///
        ///号車・・・・{0}
        ///予約期間・・・・・・{1} - {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02007 {
            get {
                return ResourceManager.GetString("KKM02007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その車両は指摘ですでに利用されています。
        ///削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02008 {
            get {
                return ResourceManager.GetString("KKM02008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の車種に関するCAP情報は閲覧許可されていないため、表示できません。
        ///閲覧あるいは編集する必要がある場合は、所属の課長・主査に設定を依頼してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02009 {
            get {
                return ResourceManager.GetString("KKM02009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の専門部門が利用している車種に関するCAP情報は閲覧許可されていないため、表示できません。
        ///閲覧あるいは編集する必要がある場合は、所属の課長・主査に設定を依頼してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02010 {
            get {
                return ResourceManager.GetString("KKM02010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のチェックボックスにチェックを入れて下さい｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02011 {
            get {
                return ResourceManager.GetString("KKM02011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に20日始業前チェック期間に登録されているスケジュールがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02012 {
            get {
                return ResourceManager.GetString("KKM02012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答期限をCAP確認済みの他の課題にも反映しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02013 {
            get {
                return ResourceManager.GetString("KKM02013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本日以降のスケジュールで仮予約のものがあります。
        ///{0}へ戻り、黄色いスケジュールを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02014 {
            get {
                return ResourceManager.GetString("KKM02014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに同じ車両の試験車使用履歴画面が開いています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02015 {
            get {
                return ResourceManager.GetString("KKM02015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去日が入力されています。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02016 {
            get {
                return ResourceManager.GetString("KKM02016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   衝突済み車両にしますか？
        ///※衝突済み車両にすることで割り当てられた駐車場が削除されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM02017 {
            get {
                return ResourceManager.GetString("KKM02017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。管理者に連絡して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03000 {
            get {
                return ResourceManager.GetString("KKM03000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました。入力内容を確認して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03001 {
            get {
                return ResourceManager.GetString("KKM03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03002 {
            get {
                return ResourceManager.GetString("KKM03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー/移動先に、同名の項目が既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03003 {
            get {
                return ResourceManager.GetString("KKM03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別の項目に移動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03004 {
            get {
                return ResourceManager.GetString("KKM03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のスケジュールと重複しないよう日付を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03005 {
            get {
                return ResourceManager.GetString("KKM03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月頭未承認のため、月末データは表示できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03006 {
            get {
                return ResourceManager.GetString("KKM03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目標進度リストが変更されています。登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03007 {
            get {
                return ResourceManager.GetString("KKM03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部署別表示中は新規作成できません。性能別表示に切り替えますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03008 {
            get {
                return ResourceManager.GetString("KKM03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の目標進度リスト名は既に存在しているため、指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03009 {
            get {
                return ResourceManager.GetString("KKM03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された日は、最終予約可能日を過ぎているため予約出来ません。
        ///他の車両をご予約下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03010 {
            get {
                return ResourceManager.GetString("KKM03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月次計画表で作成した項目のため進捗履歴は利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03011 {
            get {
                return ResourceManager.GetString("KKM03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開発符号の閲覧権限がないため、予約画面は開けません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03012 {
            get {
                return ResourceManager.GetString("KKM03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードは8文字以上13文字以内で入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03013 {
            get {
                return ResourceManager.GetString("KKM03013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDは1文字以上50文字以内で入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03014 {
            get {
                return ResourceManager.GetString("KKM03014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空車期間を検索する場合は日付を全て入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03015 {
            get {
                return ResourceManager.GetString("KKM03015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された期間に対象となるスケジュールがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03016 {
            get {
                return ResourceManager.GetString("KKM03016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ行で日付が重複しているため、登録できません。別の行に登録してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03017 {
            get {
                return ResourceManager.GetString("KKM03017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ単位の権限が存在するため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03018 {
            get {
                return ResourceManager.GetString("KKM03018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象月の月末承認がされているため、月頭承認解除はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03019 {
            get {
                return ResourceManager.GetString("KKM03019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月次計画表が承認されているため、変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03020 {
            get {
                return ResourceManager.GetString("KKM03020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日、終了日のどちらかは対象月内の日付を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03021 {
            get {
                return ResourceManager.GetString("KKM03021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ単位の権限が存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03022 {
            get {
                return ResourceManager.GetString("KKM03022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月次計画表が承認されているため、業務計画表と同期できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03023 {
            get {
                return ResourceManager.GetString("KKM03023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   課単位で表示している場合は、業務計画表と同期できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03024 {
            get {
                return ResourceManager.GetString("KKM03024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された{0}が多すぎます。{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03025 {
            get {
                return ResourceManager.GetString("KKM03025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ単位の権限が存在するため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03026 {
            get {
                return ResourceManager.GetString("KKM03026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   影響部品・出図日程入力画面は20行までしか入力できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03027 {
            get {
                return ResourceManager.GetString("KKM03027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開発符号・試作時期・号車の合計が18バイトを超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03028 {
            get {
                return ResourceManager.GetString("KKM03028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の行は過去の履歴が存在するため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03029 {
            get {
                return ResourceManager.GetString("KKM03029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終予約可能日以降にスケジュールが登録されているため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03030 {
            get {
                return ResourceManager.GetString("KKM03030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の登録権限対象は既に存在しているため、指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03031 {
            get {
                return ResourceManager.GetString("KKM03031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象は既に存在しているため、指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03032 {
            get {
                return ResourceManager.GetString("KKM03032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人、または部署・役職がすでに割り当てられているため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03033 {
            get {
                return ResourceManager.GetString("KKM03033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   車輛情報がすでに入力されています。反映してもよろしいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03034 {
            get {
                return ResourceManager.GetString("KKM03034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その管理票番号はすでに他のスケジュールで利用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03035 {
            get {
                return ResourceManager.GetString("KKM03035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集できません。
        ///編集できるのは、&quot;編集者&quot;と同じ課の方、もしくは{0}所属者のみです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03036 {
            get {
                return ResourceManager.GetString("KKM03036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03038 {
            get {
                return ResourceManager.GetString("KKM03038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03039 {
            get {
                return ResourceManager.GetString("KKM03039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートするデータがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03040 {
            get {
                return ResourceManager.GetString("KKM03040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   専門部署が入力されていないデータがあります。
        ///インポートデータを確認してください。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03041 {
            get {
                return ResourceManager.GetString("KKM03041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでにインポートされた指摘Noが含まれています。
        ///インポートデータを確認してください。
        ///
        ///指摘No：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03042 {
            get {
                return ResourceManager.GetString("KKM03042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   始業前チェックの為、予約出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03043 {
            get {
                return ResourceManager.GetString("KKM03043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03044 {
            get {
                return ResourceManager.GetString("KKM03044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指摘追加ボタンを押して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03045 {
            get {
                return ResourceManager.GetString("KKM03045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}がマスターデータに登録されていません。
        ///システム管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03046 {
            get {
                return ResourceManager.GetString("KKM03046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}以外のデータの承認欄にチェックを入れる事は出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03047 {
            get {
                return ResourceManager.GetString("KKM03047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}以外の方は承認欄にチェックを入れる事は出来ません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03048 {
            get {
                return ResourceManager.GetString("KKM03048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象車両の状況を選ばないと、指摘登録ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KKM03049 {
            get {
                return ResourceManager.GetString("KKM03049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] ReceiptFixedAssetG {
            get {
                object obj = ResourceManager.GetObject("ReceiptFixedAssetG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] ReceiptOtherT {
            get {
                object obj = ResourceManager.GetObject("ReceiptOtherT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] ReceiptTestCarG {
            get {
                object obj = ResourceManager.GetObject("ReceiptTestCarG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] ReceiptTestCarT {
            get {
                object obj = ResourceManager.GetObject("ReceiptTestCarT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   表示する列には必ず一つ以上選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00001 {
            get {
                return ResourceManager.GetString("TCM00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定列は上から順に指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00002 {
            get {
                return ResourceManager.GetString("TCM00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート順に同じ順番が指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00003 {
            get {
                return ResourceManager.GetString("TCM00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}は既に登録されています。上書きしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00004 {
            get {
                return ResourceManager.GetString("TCM00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00005 {
            get {
                return ResourceManager.GetString("TCM00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00006 {
            get {
                return ResourceManager.GetString("TCM00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00007 {
            get {
                return ResourceManager.GetString("TCM00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00008 {
            get {
                return ResourceManager.GetString("TCM00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新していない変更があります。更新しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM00009 {
            get {
                return ResourceManager.GetString("TCM00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示対象は「全て」に、◎ボタンは「全て」に変更されます。
        ///よろしいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM01001 {
            get {
                return ResourceManager.GetString("TCM01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   廃却処理してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM01002 {
            get {
                return ResourceManager.GetString("TCM01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル印刷時にエラーが発生しました。
        ///テンプレートファイルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03001 {
            get {
                return ResourceManager.GetString("TCM03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   廃却申請済であるため実行できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03002 {
            get {
                return ResourceManager.GetString("TCM03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ車体番号のデータが他にもあります（管理票NO：{0}）
        ///そのデータに新規の履歴を作成すべきではありませんか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03003 {
            get {
                return ResourceManager.GetString("TCM03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成日を入力して下さい。
        ///研命NOがAで始まる固定資産は完成日から1年後を処分予定年月とします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03004 {
            get {
                return ResourceManager.GetString("TCM03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｢かつ｣、｢または｣は必要ありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03005 {
            get {
                return ResourceManager.GetString("TCM03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｢かつ｣、｢または｣が正しく指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03006 {
            get {
                return ResourceManager.GetString("TCM03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   括弧の対応が不完全です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03007 {
            get {
                return ResourceManager.GetString("TCM03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象データがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03008 {
            get {
                return ResourceManager.GetString("TCM03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03009 {
            get {
                return ResourceManager.GetString("TCM03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認ボタンが不適切です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03010 {
            get {
                return ResourceManager.GetString("TCM03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月例点検が入力されていない月があるため申請できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03011 {
            get {
                return ResourceManager.GetString("TCM03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理待ちリストが最新状態ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03012 {
            get {
                return ResourceManager.GetString("TCM03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   衝突試験車を移管する事は出来ません。
        ///移管する必要がある場合は、1KA車両管理担当者にご相談下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03013 {
            get {
                return ResourceManager.GetString("TCM03013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中止できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03014 {
            get {
                return ResourceManager.GetString("TCM03014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成日が登録されているため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03015 {
            get {
                return ResourceManager.GetString("TCM03015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用履歴が登録されているため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03016 {
            get {
                return ResourceManager.GetString("TCM03016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件が多すぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03017 {
            get {
                return ResourceManager.GetString("TCM03017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルへのアクセスに失敗しました。
        ///ファイルを開いている場合は閉じてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03018 {
            get {
                return ResourceManager.GetString("TCM03018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用履歴の存在しない月があるため保存できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03019 {
            get {
                return ResourceManager.GetString("TCM03019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実走行距離が前月より短くなっています。
        ///間違っている場合は修正して下さい。
        ///メータ交換等の理由がある場合はその旨ご記入下さい。
        ///修正しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03020 {
            get {
                return ResourceManager.GetString("TCM03020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認処理中であるため実行できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03021 {
            get {
                return ResourceManager.GetString("TCM03021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルがほかのプログラムによって使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03022 {
            get {
                return ResourceManager.GetString("TCM03022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル印刷時にエラーが発生しました。
        ///ラベル印刷用コンポーネントをインストールしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03023 {
            get {
                return ResourceManager.GetString("TCM03023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03024 {
            get {
                return ResourceManager.GetString("TCM03024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adobe Acrobat Readerがインストールされているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03025 {
            get {
                return ResourceManager.GetString("TCM03025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   衝突試験車を流用する事は出来ません。
        ///流用する必要がある場合は、固定資産に計上してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03026 {
            get {
                return ResourceManager.GetString("TCM03026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理責任部署が登録されていないため受領票の出力ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03027 {
            get {
                return ResourceManager.GetString("TCM03027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録ナンバーが入力されています。
        ///車検期限を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03028 {
            get {
                return ResourceManager.GetString("TCM03028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一列目のチェックを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TCM03029 {
            get {
                return ResourceManager.GetString("TCM03029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] TestCarSheet {
            get {
                object obj = ResourceManager.GetObject("TestCarSheet", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
